spring.application.name=WebSocketChat
spring.mongodb.uri=mongodb+srv://aymanemwa_db_user:PX5u7zdb04OExe2R@cluster0.u3huwel.mongodb.net/chatrooms?appName=Cluster0
server.port=8080
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Health Check Settings (New 4.0 namespace)
management.endpoint.health.show-details=always
management.health.mongodb.enabled=true

# Expose Actuator over HTTP
management.endpoints.web.exposure.include=health

