spring.application.name=WebSocketChat

spring.data.mongodb.uri=${MONGODB_URI}

server.port=${SERVER_PORT:8080}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# Health Check Settings
management.endpoint.health.show-details=always
management.health.mongodb.enabled=true

# Expose Actuator
management.endpoints.web.exposure.include=health